package render

import (
	"fmt"
	"strings"
	"unicode/utf8"
)

// BuildTape generates the .tape file source for opts. outputPath is the
// absolute path VHS should write the image to.
func BuildTape(opts RenderOpts, outputPath string) (string, error) {
	opts.applyDefaults()

	var b strings.Builder
	b.WriteString("# Generated by tea-eyes — do not edit manually.\n")

	switch opts.Format {
	case "gif":
		fmt.Fprintf(&b, "Output %s\n", escapeTape(outputPath))
	default:
		// PNG: VHS still wants an Output line (any path); the real PNG comes
		// from the Screenshot command. Direct it next to the screenshot so
		// the cache directory doesn't accumulate stray gifs.
		fmt.Fprintf(&b, "Output %s\n", escapeTape(outputPath+".gif"))
	}

	fmt.Fprintf(&b, "Set Shell \"bash\"\n")
	fmt.Fprintf(&b, "Set FontFamily %s\n", escapeTape(opts.FontFamily))
	fmt.Fprintf(&b, "Set FontSize %d\n", opts.FontSize)
	fmt.Fprintf(&b, "Set Width %d\n", opts.Width*int(approxCharWidth(opts.FontSize))+opts.Padding*2)
	fmt.Fprintf(&b, "Set Height %d\n", opts.Height*int(approxLineHeight(opts.FontSize))+opts.Padding*2)
	fmt.Fprintf(&b, "Set Theme %s\n", escapeTape(opts.Theme))
	fmt.Fprintf(&b, "Set Padding %d\n", opts.Padding)

	b.WriteString("Hide\n")
	fmt.Fprintf(&b, "Type %s\n", escapeTape(buildExecLine(opts)))
	b.WriteString("Enter\n")
	b.WriteString("Show\n")
	fmt.Fprintf(&b, "Sleep %dms\n", opts.SettleMs)

	for _, spec := range opts.Keys {
		cmds, err := mapKeyToTape(spec)
		if err != nil {
			return "", fmt.Errorf("key %q: %w", spec, err)
		}
		for _, c := range cmds {
			b.WriteString(c)
			b.WriteByte('\n')
		}
		fmt.Fprintf(&b, "Sleep %dms\n", opts.SettleMs)
	}

	if opts.Format == "png" {
		fmt.Fprintf(&b, "Screenshot %s\n", escapeTape(outputPath))
	}
	return b.String(), nil
}

// buildExecLine assembles the shell command VHS types into the terminal.
// We use `exec` so the spawned process replaces bash and `q`/Ctrl+C cleanly
// terminates the recording.
func buildExecLine(opts RenderOpts) string {
	parts := []string{"exec", shellQuote(opts.Command)}
	for _, a := range opts.Args {
		parts = append(parts, shellQuote(a))
	}
	return strings.Join(parts, " ")
}

// mapKeyToTape converts a tea-eyes key spec into one or more VHS commands.
// Modifiers map onto VHS's `Ctrl+`, `Alt+`, `Shift+` prefixes; specials map
// onto the matching VHS keyword (`Enter`, `Tab`, `Up`, etc.). Anything else
// is sent as a `Type "..."` line.
func mapKeyToTape(spec string) ([]string, error) {
	if spec == "" {
		return nil, fmt.Errorf("empty key spec")
	}

	if !strings.Contains(spec, "+") {
		if v, ok := vhsSpecial(spec); ok {
			return []string{v}, nil
		}
		return []string{"Type " + escapeTape(spec)}, nil
	}

	parts := strings.Split(spec, "+")
	if !isModifier(parts[0]) {
		return []string{"Type " + escapeTape(spec)}, nil
	}

	var mods []string
	for i := 0; i < len(parts)-1; i++ {
		m := strings.ToLower(parts[i])
		if !isModifier(m) {
			return nil, fmt.Errorf("unexpected token %q (want modifier)", parts[i])
		}
		mods = append(mods, modifierToVHS(m))
	}
	keyName := parts[len(parts)-1]
	if keyName == "" {
		return nil, fmt.Errorf("missing key after modifier")
	}

	if v, ok := vhsSpecial(keyName); ok {
		// e.g. Shift+Tab → "Shift+Tab" (VHS supports Shift+Tab as a single token)
		return []string{strings.Join(mods, "") + v}, nil
	}
	if utf8.RuneCountInString(keyName) == 1 {
		return []string{strings.Join(mods, "") + keyName}, nil
	}
	return nil, fmt.Errorf("unknown key %q", keyName)
}

func isModifier(s string) bool {
	switch strings.ToLower(s) {
	case "ctrl", "alt", "shift", "meta":
		return true
	}
	return false
}

func modifierToVHS(m string) string {
	switch m {
	case "ctrl":
		return "Ctrl+"
	case "alt", "meta":
		return "Alt+"
	case "shift":
		return "Shift+"
	}
	return ""
}

// vhsSpecial returns the VHS keyword for a special key name, if recognized.
func vhsSpecial(name string) (string, bool) {
	switch strings.ToLower(name) {
	case "enter", "return":
		return "Enter", true
	case "escape", "esc":
		return "Escape", true
	case "tab":
		return "Tab", true
	case "space":
		return "Space", true
	case "backspace":
		return "Backspace", true
	case "up":
		return "Up", true
	case "down":
		return "Down", true
	case "left":
		return "Left", true
	case "right":
		return "Right", true
	case "home":
		return "Home", true
	case "end":
		return "End", true
	case "pgup", "pageup":
		return "PageUp", true
	case "pgdown", "pagedown":
		return "PageDown", true
	case "delete", "del":
		return "Delete", true
	case "insert", "ins":
		return "Insert", true
	}
	if len(name) >= 2 && (name[0] == 'f' || name[0] == 'F') {
		// f1..f12 → F1..F12
		rest := name[1:]
		for _, r := range rest {
			if r < '0' || r > '9' {
				return "", false
			}
		}
		return "F" + rest, true
	}
	return "", false
}

// escapeTape wraps a string in double quotes for use in a .tape file.
func escapeTape(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}

// shellQuote single-quotes s for the inner `exec ...` shell line. Bubble-tea
// binaries rarely need anything fancier; embedded single quotes are escaped
// via the standard '"'"' trick.
func shellQuote(s string) string {
	if s == "" {
		return "''"
	}
	if safeShellWord(s) {
		return s
	}
	return "'" + strings.ReplaceAll(s, "'", `'"'"'`) + "'"
}

func safeShellWord(s string) bool {
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z',
			r >= 'A' && r <= 'Z',
			r >= '0' && r <= '9',
			r == '_', r == '-', r == '.', r == '/', r == '=':
		default:
			return false
		}
	}
	return true
}

// approxCharWidth/approxLineHeight are rough font metrics used to size the
// VHS canvas. They don't need to be exact — the test allows ±50px slack.
func approxCharWidth(fontSize int) float64  { return float64(fontSize) * 0.6 }
func approxLineHeight(fontSize int) float64 { return float64(fontSize) * 1.3 }
