package teatest

import (
	"bytes"
	"fmt"
	"text/template"
)

const harnessFileName = "zz_tea_eyes_harness_test.go"

// resultSentinelStart and resultSentinelEnd bracket the JSON result line the
// harness prints. They must be distinctive enough to survive `go test -v`
// framing.
const (
	resultSentinelStart = "<<TEA_EYES_RESULT>>"
	resultSentinelEnd   = "<<TEA_EYES_END>>"
)

// harnessTemplate is rendered into the user's package as a build-tagged test
// file. It reads runtime inputs from environment variables so a single cached
// test binary can serve many invocations.
const harnessTemplate = `//go:build teaeyes

// Code generated by tea-eyes. DO NOT EDIT.

package {{.PackageName}}

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"reflect"
	"strconv"
	"strings"
	"testing"
	"time"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
	"github.com/charmbracelet/x/exp/teatest"
	"github.com/muesli/termenv"
)

func teaEyesAtoi(s string, def int) int {
	if s == "" {
		return def
	}
	n, err := strconv.Atoi(s)
	if err != nil {
		return def
	}
	return n
}

func teaEyesProfile(name string) termenv.Profile {
	switch strings.ToLower(name) {
	case "truecolor":
		return termenv.TrueColor
	case "ansi256":
		return termenv.ANSI256
	case "ansi":
		return termenv.ANSI
	default:
		return termenv.Ascii
	}
}

func teaEyesSend(tm *teatest.TestModel, spec string) {
	switch strings.ToLower(spec) {
	case "enter", "return":
		tm.Send(tea.KeyMsg{Type: tea.KeyEnter})
	case "space":
		tm.Send(tea.KeyMsg{Type: tea.KeySpace})
	case "tab":
		tm.Send(tea.KeyMsg{Type: tea.KeyTab})
	case "shift+tab":
		tm.Send(tea.KeyMsg{Type: tea.KeyShiftTab})
	case "esc", "escape":
		tm.Send(tea.KeyMsg{Type: tea.KeyEsc})
	case "backspace":
		tm.Send(tea.KeyMsg{Type: tea.KeyBackspace})
	case "delete", "del":
		tm.Send(tea.KeyMsg{Type: tea.KeyDelete})
	case "up":
		tm.Send(tea.KeyMsg{Type: tea.KeyUp})
	case "down":
		tm.Send(tea.KeyMsg{Type: tea.KeyDown})
	case "left":
		tm.Send(tea.KeyMsg{Type: tea.KeyLeft})
	case "right":
		tm.Send(tea.KeyMsg{Type: tea.KeyRight})
	case "home":
		tm.Send(tea.KeyMsg{Type: tea.KeyHome})
	case "end":
		tm.Send(tea.KeyMsg{Type: tea.KeyEnd})
	case "pgup", "pageup":
		tm.Send(tea.KeyMsg{Type: tea.KeyPgUp})
	case "pgdown", "pagedown":
		tm.Send(tea.KeyMsg{Type: tea.KeyPgDown})
	case "ctrl+c":
		tm.Send(tea.KeyMsg{Type: tea.KeyCtrlC})
	default:
		tm.Type(spec)
	}
}

func teaEyesModelToJSON(m tea.Model) string {
	if m == nil {
		return "null"
	}
	v := reflect.ValueOf(m)
	for v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return "null"
		}
		v = v.Elem()
	}
	if v.Kind() != reflect.Struct {
		b, _ := json.Marshal(m)
		return string(b)
	}
	out := map[string]any{}
	t := v.Type()
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if !f.IsExported() {
			continue
		}
		fv := v.Field(i)
		out[f.Name] = fv.Interface()
	}
	b, err := json.Marshal(out)
	if err != nil {
		return fmt.Sprintf("%q", err.Error())
	}
	return string(b)
}

func TestTeaEyesHarness(t *testing.T) {
	op := os.Getenv("TEA_EYES_OP")
	if op == "" {
		t.Skip("TEA_EYES_OP not set; harness invoked outside tea-eyes driver")
	}

	width := teaEyesAtoi(os.Getenv("TEA_EYES_WIDTH"), 80)
	height := teaEyesAtoi(os.Getenv("TEA_EYES_HEIGHT"), 24)
	profile := teaEyesProfile(os.Getenv("TEA_EYES_COLOR"))
	lipgloss.SetColorProfile(profile)

	var keys []string
	if raw := os.Getenv("TEA_EYES_KEYS"); raw != "" {
		if err := json.Unmarshal([]byte(raw), &keys); err != nil {
			t.Fatalf("TEA_EYES_KEYS not valid JSON array: %v", err)
		}
	}

	m := {{.ModelFunc}}()
	tm := teatest.NewTestModel(t, m, teatest.WithInitialTermSize(width, height))

	for _, k := range keys {
		teaEyesSend(tm, k)
		time.Sleep(20 * time.Millisecond)
	}

	// Ask the program to quit so FinalOutput can complete. If the keys above
	// already triggered tea.Quit, this is a harmless no-op.
	_ = tm.Quit()

	finalModel := tm.FinalModel(t, teatest.WithFinalTimeout(5*time.Second))
	out, _ := io.ReadAll(tm.FinalOutput(t, teatest.WithFinalTimeout(5*time.Second)))

	result := map[string]any{
		"final_output": string(out),
	}
	if op == "inspect" {
		result["model_json"] = teaEyesModelToJSON(finalModel)
		view := ""
		if finalModel != nil {
			view = finalModel.View()
		}
		result["view_text"] = view
	}

	b, err := json.Marshal(result)
	if err != nil {
		t.Fatalf("marshal result: %v", err)
	}
	fmt.Println("` + resultSentinelStart + `" + string(b) + "` + resultSentinelEnd + `")
}
`

type harnessTemplateData struct {
	PackageName string
	ModelFunc   string
}

func renderHarness(packageName, modelFunc string) ([]byte, error) {
	tmpl, err := template.New("harness").Parse(harnessTemplate)
	if err != nil {
		return nil, fmt.Errorf("teatest: parse harness template: %w", err)
	}
	var buf bytes.Buffer
	if execErr := tmpl.Execute(&buf, harnessTemplateData{
		PackageName: packageName,
		ModelFunc:   modelFunc,
	}); execErr != nil {
		return nil, fmt.Errorf("teatest: render harness: %w", execErr)
	}
	return buf.Bytes(), nil
}
